app:
    resource: "@AppBundle/Controller/"
    type:     annotation

poster:
    resource: "@PosterBundle/Controller/"
    type:     annotation

map:
    resource: "@MapBundle/Controller/"
    type:     annotation
    
homepage:
    path: /
    defaults:
        _controller: AppBundle:Main:homepage
